spring.cloud.function.definition=employeeProducer;employeeResultConsumer

# PRODUTOR: Envia para employee-events
spring.cloud.stream.bindings.employeeProducer-out-0.destination=employee-events

# CONSUMIDOR: Escuta employee-results (Onde Payroll e DB publicam)
spring.cloud.stream.bindings.employeeResultConsumer-in-0.destination=employee-results
spring.cloud.stream.bindings.employeeResultConsumer-in-0.group=crud-group