spring.cloud.stream.default-binder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# PRODUTOR: Forca a criacao da exchange como TOPIC e define a chave de envio
spring.cloud.stream.rabbit.bindings.employeeProducer-out-0.producer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.employeeProducer-out-0.producer.routingKeyExpression='employee.created'

# CONSUMIDOR: CRUD quer ouvir TUDO (#)
spring.cloud.stream.rabbit.bindings.employeeResultConsumer-in-0.consumer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.employeeResultConsumer-in-0.consumer.bindingRoutingKey=#