spring.cloud.function.definition=sagaCommandProducer;sagaReplyConsumer

spring.cloud.stream.bindings.sagaCommandProducer-out-0.destination=saga-commands

spring.cloud.stream.bindings.sagaReplyConsumer-in-0.destination=saga-replies
spring.cloud.stream.bindings.sagaReplyConsumer-in-0.group=crud-orchestrator