# --- GERAIS ---
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.level.org.springframework.web=INFO

#---
# PROFILE: COREOGRAFIA
spring.config.activate.on-profile=choreography
spring.cloud.function.definition=validateSalary
spring.cloud.stream.bindings.validateSalary-in-0.destination=employee-events
spring.cloud.stream.bindings.validateSalary-in-0.group=payroll-group
spring.cloud.stream.bindings.validateSalary-out-0.destination=employee-results

#---
# PROFILE: ORQUESTRAÇÃO
spring.config.activate.on-profile=orchestration
spring.cloud.function.definition=processSalaryCommand
spring.cloud.stream.bindings.processSalaryCommand-in-0.destination=saga-commands
spring.cloud.stream.bindings.processSalaryCommand-in-0.group=payroll-group
spring.cloud.stream.bindings.processSalaryCommand-out-0.destination=saga-replies

#---
# PROFILE: RABBIT (Define RabbitMQ como o broker ativo)
spring.config.activate.on-profile=rabbit
spring.cloud.stream.default-binder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

#---
# PROFILE: KAFKA (Define Kafka como o broker ativo)
spring.config.activate.on-profile=kafka
spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092